compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-sources.cjs
